#!/usr/bin/env bash
# custom 404 page

sudo apt update
sudo apt-get -y install nginx
touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '25 i \\terror_page 404 /404.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
