#!/usr/bin/env bash
#  configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "24 i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"\
/etc/nginx/sites-enabled/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "26 i \\\terror_page 404 /404.html;" /etc/nginx/sites-enabled/default
sudo sed -i "30 i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
