#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt install -y haproxy
sudo sed -i "$ aENABLED=1" /etc/default/haproxy
echo "
frontend load_balancer
	bind *:80
	mode http
	default_backend webserver
backend webserver
	balance roundrobin
	server 3239-web-01 3.84.126.138 check
	server 3239-web-02 54.145.55.42 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
